In [1]:
import emoji
text = '😂'


In [2]:
emoji.demojize(text)

':face_with_tears_of_joy:'

In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.DataFrame(
    {
        'review':[
            np.array([1,2,3,4,5]),
            np.array([2,3,4,7,8]),
            np.array([6,3,8,9,2])
        ],
        'sentiment':[0,1,0]
    }
)

In [14]:
df

review  sentiment
0  [1, 2, 3, 4, 5]          0
1  [2, 3, 4, 7, 8]          1
2  [6, 3, 8, 9, 2]          0

In [15]:
X = np.array(df['review'].tolist())
y = np.array(df['sentiment'].tolist())

In [16]:
X

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 7, 8],
       [6, 3, 8, 9, 2]])

In [17]:
y

array([0, 1, 0])

In [18]:
type(X)

numpy.ndarray

In [19]:
X.shape

(3, 5)

In [20]:
y.shape

(3,)

In [21]:
dic={
    'X':X,
    'y':y
}

In [22]:
dic['X']

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 7, 8],
       [6, 3, 8, 9, 2]])

In [4]:
text = "hesl;fj        dgkdogkd;lgvk;      s;kf;fk"

In [5]:
ls=text.split()

In [6]:
" ".join(ls)

'hesl;fj dgkdogkd;lgvk; s;kf;fk'